wooga/atlas-release

src/main/groovy/wooga/gradle/release/ReleasePlugin.groovy

`publish` task must run after `release` task
`githubPublish` should not create the release tag before the release task tries to do so.

Fix publish task dependency

---

build.gradle

This new version includes dedicated log output for all major
paket commands, and a new task `paketOutdated`

Bump net.wooga.paket version to 0.7.0

---

src/main/groovy/wooga/gradle/release/ReleasePlugin.groovy
src/main/groovy/wooga/gradle/release/WoogaStrategies.groovy
src/test/groovy/wooga/gradle/release/ReleasePluginSpec.groovy

This will help during development when patch releases are created and
our integration counter is reseted.

Set default release.scope to patch

---

build.gradle
src/main/groovy/wooga/gradle/release/ReleasePlugin.groovy
src/main/groovy/wooga/gradle/release/utils/ReleaseBodyStrategy.groovy
src/main/groovy/wooga/gradle/release/utils/ReleaseNotesGenerator.groovy
src/test/groovy/wooga/gradle/release/utils/ReleaseBodyStrategySpec.groovy
src/test/groovy/wooga/gradle/release/utils/ReleaseNotesGeneratorTest.groovy

This pull request adds helper logic to create nice default release notes.
Right after the release tag is created the github publish task will ask for the release body value. This value is provided via a custom `PublishBodyStrategy` implementation. 
```groovy
interface PublishBodyStrategy {
String getBody(GHRepository repository)
}
```
This new class will take the provided `GHRepository` parameter in `getBody` together with the given `GrGit` and `ReleaseVersion` objects and feed it to the new utility class `ReleaseNotesGenerator`.
The `ReleaseNotesGenerator` will execute several steps to build the notes body string:
* retrieve a list of commits between the current and last version
* scan these commit messages for pull request merge commits. (maked with `#number`)
* read the `change list` …

Custom GitHub release body

---

build.gradle
src/main/groovy/wooga/gradle/release/ReleasePlugin.groovy

Description
-----------
Update dependency `net.wooga.atlas-github` to version `0.4.0` which
allows lazy property setting.
Set `isPrerelease` for github publish task only when `project.status` is
not `release`
Closes #7 
Changes
-------
* ![UPDATE] [`net.wooga.atlas-github`](https://github.com/wooga/atlas-github/releases/tag/v0.4.0) to version `0.4.0`
* ![IMPROVE] github publish task setup. Set `isPrerelease` property.
[NEW]:http://atlas-resources.wooga.com/icons/icon_new.svg "New"
[ADD]:http://atlas-resources.wooga.com/icons/icon_add.svg "Add"
[IMPROVE]:http://atlas-resources.wooga.com/icons/icon_improve.svg "IMPROVE"
[CHANGE]:http://atlas-resources.wooga.com/icons/icon_change.svg "Change"
[FIX]:http://atlas-resources.wooga.com/icons/icon_fix.svg "Fix" …

Set github release isPrerelease as lazy value

---

src/main/groovy/wooga/gradle/release/utils/ReleaseNotesGenerator.groovy
src/test/groovy/wooga/gradle/release/utils/ReleaseNotesGeneratorTest.groovy

In the case of an exception during `getPullRequest` in
`fetchPullRequestsFromLog`, return null instead of crashing.

Fix case when pull request can't be loaded

---

README.md
RELEASE_NOTES.md
src/main/resources/iconlist.mustache
src/test/groovy/wooga/gradle/release/utils/ReleaseNotesGeneratorTest.groovy

Use proper `https` URL to change set icons
* ![FIX] changeset icon base URL `resources.atlas` -> `atlas-resources`
* ![FIX] changeset icon URL protocol to `https`
[NEW]:http://resources.atlas.wooga.com/icons/icon_new.svg "New" …

Fix base url for change set icons

---

src/integrationTest/groovy/wooga/gradle/release/GithubIntegration.groovy
src/integrationTest/groovy/wooga/gradle/release/ReleaseNotesGenerationIntegrationSpec.groovy
src/integrationTest/groovy/wooga/gradle/release/ReleaseNotesUpdateIntegrationSpec.groovy
src/main/groovy/wooga/gradle/release/tasks/UpdateReleaseNotes.groovy
src/main/groovy/wooga/gradle/release/utils/ReleaseNotesGenerator.groovy

The body values for pull requests retrieved via the github API are not
normalized. The generator creates files in a mix line ending mode.
Together with the append method, which will push the changes directly to
github without any git `clean/smudge` settings applied, this leads to a
bad user expirience when pulling these changes.
[NEW]:http://resources.atlas.wooga.com/icons/icon_new.svg "New" …

Normalize release note text after generation

---

src/main/groovy/wooga/gradle/release/utils/ReleaseNoteBody.groovy
src/test/groovy/wooga/gradle/release/utils/ReleaseNotesGeneratorTest.groovy

Strip changeset icon url links from pull request bodies along with html
comments and whitespaces
* ![FIX] duplicate changeset icon links in generated notes
[NEW]:http://resources.atlas.wooga.com/icons/icon_new.svg "New" …

Cleanup multiple changeset icon links

---

.gitignore
src/integrationTest/groovy/wooga/gradle/release/GithubIntegration.groovy
src/integrationTest/groovy/wooga/gradle/release/ReleaseNotesGenerationIntegrationSpec.groovy
src/main/groovy/wooga/gradle/release/utils/ReleaseNoteBody.groovy
src/main/groovy/wooga/gradle/release/utils/ReleaseNotesGenerator.groovy
src/main/resources/dependency.mustache
src/main/resources/releaseNote.mustache
src/test/groovy/wooga/gradle/release/utils/ReleaseBodyStrategySpec.groovy
src/test/groovy/wooga/gradle/release/utils/ReleaseNotesGeneratorTest.groovy
src/test/groovy/wooga/gradle/release/utils/TestContent.groovy

Adds dependencies with version defined in a `paket.template` file (if available) to each release block in generated release notes. Fixes #13 
**Example**
```bash
Wooga.TestDependency1 ~> 0.2.0
Wooga.TestDependency2 = 0.8
Wooga.TestDependency3 
Wooga.TestDependency4 master
Wooga.TestDependency4 > 1, <2
```

Add paket dependencies to release notes

---

src/main/groovy/wooga/gradle/release/utils/ReleaseNotesGenerator.groovy
src/test/groovy/wooga/gradle/release/utils/ReleaseNotesGeneratorTest.groovy

To find all closed pull requests withing one release cycle, the
`ReleaseNotesGenerator` collected all commits with the pattern `#(\d+)`.
The problem are commit messages with multiple hash signs. This can
happen when developers mark issues within the message or a pullrequest
title. This change allows to mark multiple pull requests with one commit
message.
* ![FIX] method `fetchPullRequestsFromLog` to allow multiple `#n` patterns in message
fixes #19  …

Fix ReleaseNoteGenerator handle multiple hashsigns in commit message

---

src/integrationTest/groovy/wooga/gradle/release/ReleaseNotesUpdateIntegrationSpec.groovy
src/main/groovy/wooga/gradle/release/tasks/UpdateReleaseNotes.groovy

If a repository does not contain a release notes file
then create it when retrieving it from github fails.
* ![FIX] ensure release notes file on update
fixes #18  …

Ensure release notes file on repository

---

src/integrationTest/groovy/wooga/gradle/release/ReleasePluginIntegrationSpec.groovy
src/main/groovy/wooga/gradle/release/AtlasReleasePluginExtension.groovy
src/main/groovy/wooga/gradle/release/ReleasePlugin.groovy
src/test/groovy/wooga/gradle/release/ReleasePluginSpec.groovy

Some packages might need to adjust the `cleanMetaFiles` file pattern
because they want to add meta files for folders or asset bundles
This pullrequest makes this filter configurable
**build.gradle**
```groovy
atlasRelease.metaCleanPattern {
include("**/*.cs")
include("**/*.json")
exclude("**/*.dll.meta")
exclude("**/keep/*.cs.meta")
exclude("**/keep/*.json.meta")
exclude("**/keep/.meta")
}
```
The old pattern is applied by default:
```groovy
extension.metaCleanPattern {
include("**/*.meta")
exclude("**/*.dll.meta")
exclude("**/*.so.meta")
}
``` …

Add configureable meta clean pattern

---

build.gradle
gradle/wrapper/gradle-wrapper.properties

The `net.wooga.paket` plugin had some interesting changes. This pull
request applies the latest version of this plugin. The development
`build.gradle` switched to the `net.wooga.plugins` plugin as a base to
remove all the verbose integration tests setups. …

Update plugin dependencies

---

src/integrationTest/groovy/wooga/gradle/release/ReleasePluginIntegrationSpec.groovy
src/main/groovy/wooga/gradle/release/ReleasePlugin.groovy
src/test/groovy/wooga/gradle/release/ReleasePluginSpec.groovy

The `NebularRelease` plugin will provide slightly better error messages when using the official
cli tasks (final, candidate, snapshot, ...). Because of internal naming reasons it makes sense for us to use `rc` instead of `candidate`. All other resources are named with the
pattern (final, rc and snapshot). I used a custom task with the name `rc` which depends on
`candidate` but this will fall through the error check in `NebularRelease`. So instead we
now change the cli tasklist on the fly. If we find the `rc` taskname in the cli tasklist we remove it
and add `candidate` instead. …

Fix error messages for rc builds

---

build.gradle
src/integrationTest/groovy/wooga/gradle/release/ReleasePluginIntegrationSpec.groovy
src/main/groovy/wooga/gradle/release/ReleasePlugin.groovy
src/test/groovy/wooga/gradle/release/ReleasePluginSpec.groovy

We discovered a Bug where the setup task of a subproject with plugin `net.wooga.wdk-unity` didn't get called. 
We check for Plugin existence in all subprojects and call setup task if available.
Fixes #26

Ensure Sub Project Setup task gets called

---

docs/api/wooga/gradle/release/WoogaStrategies.html
src/integrationTest/groovy/wooga/gradle/release/ReleasePluginIntegrationSpec.groovy
src/main/groovy/wooga/gradle/release/AtlasReleasePluginExtension.groovy
src/main/groovy/wooga/gradle/release/ReleasePlugin.groovy
src/main/groovy/wooga/gradle/release/internal/DefaultAtlasReleasePluginExtension.groovy
src/main/groovy/wooga/gradle/release/utils/WoogaStrategies.groovy
src/test/groovy/wooga/gradle/release/ReleasePluginSpec.groovy

This pull requst update the package layout to have he same structural layout as all other `wooga` plugins. It also adds groovy documentation strings.
#29  …

Restructure package layout and add groovy docs

---

build.gradle
src/integrationTest/groovy/wooga/gradle/release/ReleasePluginIntegrationSpec.groovy
src/main/groovy/wooga/gradle/release/ReleasePlugin.groovy

For a more robust build setup we should switch to `paket restore` as the default dependency installation command. The command `paket install` could trigger changes if a dev changed the `paket.dependencies` file but not commting the `paket.lock` file. Alternativly the `paket restore`
command only installs dependencies listed in `paket.lock`. It even fails when no lock file exists. To counter this behavior, we will switch to `paket install` when no lock file is available.
resolves #36  …

Use paket restore during setup

---

src/integrationTest/groovy/wooga/gradle/release/ReleaseStepsIntegrationSpec.groovy
src/main/groovy/wooga/gradle/release/ReleasePlugin.groovy

The `BaseReleasePlugin` will automatically push the current branch when the name != `HEAD`. This leads for us to some funny sideeffects on the Jenkins machines. This behavior is not configurable at this time. What this pull request does is override the `release` task action and provide a more conservative implementaton.
resolves #37 
While implementing this I was wondering if we really want to stop every push or should make this somehow configurable on our side. …

Fix branch push during release

---

build.gradle
src/main/groovy/wooga/gradle/release/ReleasePlugin.groovy

As a preparation for the `1.x` release of this package I updated the underlying dependency to Nebular Release.
[ANDROID]:http://resources.atlas.wooga.com/icons/icon_android.svg "Android" …

Update Nebular Release plugin dependency to 6.+

---

src/main/groovy/wooga/gradle/release/version/semver2/VersionStrategies.groovy

The new semver v2 snapshot strategy doesn't get applied when the current stage == `SNAPSHOT`. Since we want to have backwards compatibility to switch from v1 to v2 this must be fixed
* ![FIX] semver v2 snapshot strategy …

Fix semver v2 snapshot strategy

---

src/main/groovy/wooga/gradle/release/version/semver2/VersionStrategies.groovy
src/test/groovy/wooga/gradle/release/ReleasePluginSpec.groovy

The new `semver 2.0` snapshot strategy enforces version precedence due to a configuration error. This is a clear bug because snapshot builds are designed to be outside the version order for `rc` or `final` builds. So how can this bug show itself. The only valid way at the moment to trigger this bug is to build a prerelease build (`rc`) and then a snapshot version with the same base version. This can happen in `release/2.x` branches. A snapshot build should have no direct connections to any pre or final release.
**gradle output**
```
> Inferred version (2.0.0-branch.release.2.x.0) cannot be lower than nearest (2.0.0-rc.1). Required by selected strategy.
```
This patch simply configures the snapshot strategy not to enforce version precedence (the old v1 did this as well). …

Fix version precedence check for snapshot (ci) builds

---

src/main/groovy/wooga/gradle/release/version/semver2/VersionStrategies.groovy

This patch sets the `allowDirtyRepo` flag for all semver 2.0 strategies to `true`. This check makes more problems than it solved in reality. Another patch might add a warning instead of a hard fail. …

Allow dirty repo in all semver 2.0 strategies

---

build.gradle

The 0. version range should never be declared with a range since any new minor release can contain breaking changes. We need to pin to a compatible version and update
manually or through use of dependabot.
* ![FIX] pin unstable version of `com.wooga.gradle:gradle-commons-test`
[BREAK]:    https://resources.atlas.wooga.com/icons/icon_break.svg "Remove" …

Pin version of com.wooga.gradle:gradle-commons-test

---

build.gradle
src/integrationTest/groovy/wooga/gradle/release/ReleasePluginIntegrationSpec.groovy
src/main/groovy/wooga/gradle/release/ReleasePlugin.groovy
src/test/groovy/wooga/gradle/release/ReleasePluginSpec.groovy

Adds support for the preflight release stage.
* ![ADD] Support for the newer `preflight` release stage, as a task
* ![UPDATE] `atlas-version` to `1.1+`, as it includes the newer release stage and wdk strategy.
[BREAK]:    https://resources.atlas.wooga.com/icons/icon_break.svg "Remove"
[REMOVE]:   https://resources.atlas.wooga.com/icons/icon_remove.svg …

Adds the preflight release_stage

---

src/main/groovy/wooga/gradle/release/ReleasePlugin.groovy

Add  an empty `preflight` task for compatibility reasons with the calling jenkins pipeline.
* ![ADD] `prefligh` publish task
[BREAK]:    https://resources.atlas.wooga.com/icons/icon_break.svg "Remove"
[REMOVE]:   https://resources.atlas.wooga.com/icons/icon_remove.svg "Remove"
[IOS]:      https://resources.atlas.wooga.com/icons/icon_iOS.svg "iOS" …

Add preflight publish task

---

Jenkinsfile
build.gradle
settings.gradle

This patch adds snyk monitoring to the build pipeline. It will hook itself into the check and publish stages.
The patch also sets a dependency helper plugin net.wooga.cve-dependency-resolution which applies overrides for dependencies with know fixes for security issues.
* ![ADD] `snyk` monitoring
* ![ADD] `net.wooga.snyk-wdk-java` snyk convention plugin
* ![ADD] `net.wogoa.cve-dependency-resolution` plugin
[UPDATE]: …

Add snyk monitoring [ATLAS-702]

---

Jenkinsfile
build.gradle

Because of security issues reported for the coveralls gradle plugin I decided to remove the feature during build. It is not enough to just stop sending reports via jenkins. We also need to update to `net.wooga.plugins` > `4.0.0` because this version removes the dependency.
I remove the coveralls token in the Jenkinsfile so our base pipeline won't try to call the coveralls task on the gradle project.
* ![UPDATE] `net.wooga.plugins` to version `4.0.0` to remove coveralls dependency
* ![REMOVE] coveralls token in Jenkinsfile
[CHANGE]: …

Remove coveralls reporting [ATLAS-753]

---

build.gradle

For the new UPM wrapper packages we need to make sure that the build uses at least version 3.1 of `net.wooga.paket`.
* ![UPDATE] `net.wooga.paket` to min version `3.1`
[BREAK]:    https://resources.atlas.wooga.com/icons/icon_break.svg "Remove"
[REMOVE]:   https://resources.atlas.wooga.com/icons/icon_remove.svg "Remove"
[IOS]: …

Update net.wooga.paket to min version 3.1

---

src/integrationTest/groovy/wooga/gradle/release/ReleasePluginIntegrationSpec.groovy
src/main/groovy/wooga/gradle/release/ReleasePlugin.groovy

We have a new bug where some unity tasks get executed before the paket unity install tasks had any chance to be executed. This patch is addressing this by making sure that any task of type `wooga.gradle.unity.UnityTask` depends on
* `paketUnityInstall`
* `paketUnityUnwrapUPMPackages`
* ![FIX] execution order of Unity tasks in sub modules
[BREAK]: …

Fix execution order of Unity tasks in sub modules

---

src/integrationTest/groovy/wooga/gradle/release/ReleasePluginIntegrationSpec.groovy
src/main/groovy/wooga/gradle/release/ReleasePlugin.groovy
src/test/groovy/wooga/gradle/release/ReleasePluginSpec.groovy

[ATLAS-1451](https://woogagmbh.atlassian.net/browse/ATLAS-1451)
Make sure release plugin can be added after wdk-release plugin by not creating the same tasks.
Add support for the root-level folder structure for configuring the unity package.
* ![IMPROVE] Optionally add tasks to support co-existence with wdk-release plugin
* ![CHANGE] Add support for the root-level folder structure for configuring the unity package
[UPDATE]: …

Root-Level Project Support + WDK-Release tasks collision fix [ATLAS-1451]
